// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wviyrtdytypbjkrvwkxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2aXlydGR5dHlwYmprcnZ3a3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDg3MDUsImV4cCI6MjA2ODQ4NDcwNX0.GIQxAt4duwl8X-A6e7ixdWCWguTDwSj4MZfdap3MFFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});